version: '3.8'

services:
  neo4j:
    image: neo4j:4.4
    container_name: neo4j
    ports:
      - 7474:7474  # HTTP port
      - 7687:7687  # Bolt port
    environment:
      - NEO4J_AUTH=neo4j/your_secure_password
    volumes:
      - neo4j_data:/data

volumes:
  neo4j_data:
